"""下载、Factory I/O、流水线工具"""
import os
import subprocess
from _helpers import (
    mcp, _run_python, _format_result, _check_project,
    PROJECT_PATH, PLCSIM_INSTANCE, PLC_IP,
    DOWNLOAD_SCRIPT, P3_SCRIPT, cfg,
)


@mcp.tool(name="plc_download_project", annotations={"destructiveHint": True})
async def download_project(method: str = "auto", compile_first: bool = True) -> str:
    """将 TIA Portal 项目下载到 PLCSIM（自动选择最优方式）

    Args:
        method: 下载方式 (auto/tiaworker/tiaworker-gui/python/ui/golden-restore)
        compile_first: 下载前是否先编译
    """
    if err := _check_project(): return err

    method_map = {
        "auto": [],
        "tiaworker": ["--tiaworker"],
        "tiaworker-gui": ["--tiaworker-gui"],
        "python": ["--python"],
        "ui": ["--ui"],
        "golden-restore": ["--golden-restore"],
    }
    extra_args = method_map.get(method, [])
    if compile_first and method == "auto":
        extra_args = ["--compile-first"]

    if method == "golden-restore":
        result = _run_python(DOWNLOAD_SCRIPT, ["--golden-restore"], timeout=120)
        return _format_result(result.get("success"), error=result.get("error", "恢复失败"))

    result = _run_python(DOWNLOAD_SCRIPT, extra_args, timeout=300)
    return _format_result(result.get("success"), data={
        "method": method,
        "output": result.get("output", "")[:500],
    }, error=result.get("error", "下载失败"))


@mcp.tool(name="plc_fio_write_config", annotations={"destructiveHint": False})
async def fio_write_config(
    instance_name: str = "",
    auto_connect: bool = True,
    run_mode: bool = True,
) -> str:
    """写入 Factory I/O 的 auto.cfg 配置文件

    Args:
        instance_name: PLCSIM 实例名
        auto_connect: 是否自动连接
        run_mode: 场景启动时是否直接运行
    """
    name = instance_name or PLCSIM_INSTANCE

    cfg_text = f"""# Factory I/O auto config — generated by plc_mcp_bridge
ui.show_welcome_window = False
scene.start_in_run_mode = {str(run_mode).lower()}
drivers.siemens_s7plcsim.auto_connect = {str(auto_connect).lower()}
drivers.siemens_s7plcsim.instance_name = '{name}'
drivers.siemens_s7plcsim.connection_timeout = 60
"""
    written = []
    for p in [
        r'C:\ProgramData\Real Games\Factory IO\auto.cfg',
        os.path.join(os.path.expanduser('~'), 'Documents', 'Factory IO', 'auto.cfg'),
    ]:
        try:
            os.makedirs(os.path.dirname(p), exist_ok=True)
            with open(p, 'w', encoding='utf-8-sig') as f:
                f.write(cfg_text)
            written.append(p)
        except Exception:
            pass

    if written:
        return f"✅ auto.cfg 已写入 ({len(written)} 个位置)"
    return "! 无法写入 auto.cfg（权限不足？）"


@mcp.tool(name="plc_fio_launch", annotations={"destructiveHint": False})
async def fio_launch(fio_path: str = "", scene_path: str = "") -> str:
    """启动 Factory I/O（需要先通过 fio_write_config 配置连接）"""
    exe = fio_path or (str(cfg.factory_io.exe_path) if cfg else "")
    if not exe:
        return "❌ 未配置 Factory I/O 路径"
    if not os.path.exists(exe):
        return f"❌ Factory I/O 未找到: {exe}"
    try:
        subprocess.Popen([exe, scene_path] if scene_path else [exe], shell=True)
        return "✅ Factory I/O 已启动"
    except Exception as e:
        return f"❌ 启动失败: {e}"


@mcp.tool(name="plc_run_pipeline", annotations={"destructiveHint": True})
async def run_pipeline(skip_compile: bool = False, launch_fio: bool = True) -> str:
    """运行完整的 P3 端到端流水线

    流程:
      1. PLCSIM golden 恢复 → STOP 待下载
      2. 编译 TIA 项目
      3. 下载到 PLCSIM（5 级降级自动选择最佳方式）
      4. 更新 golden backup
      5. 启动 Factory I/O

    Args:
        skip_compile: 跳过编译步骤
        launch_fio: 完成后启动 Factory I/O
    """
    result = _run_python(
        P3_SCRIPT,
        ["--skip-compile"] if skip_compile else [],
        timeout=600,
    )
    out = result.get("output", "")
    if result.get("success") is False and not out:
        return _format_result(False, error=result.get("error", "流水线执行失败"))
    return f"流水线结果:\n{out[:1000]}" if out else "✅ 流水线完成"


@mcp.tool(name="plc_golden_restore", annotations={"destructiveHint": True})
async def golden_restore() -> str:
    """快速恢复模式：直接从 golden backup 恢复 PLCSIM，跳过编译/下载

    适用于:
      - 已知 golden backup 已包含最新程序
      - 只需重置 PLCSIM 到已知状态
      - TIA Portal 不需要打开
    """
    result = _run_python(P3_SCRIPT, ["--golden-restore"], timeout=120)
    out = result.get("output", "")
    return out if out else _format_result(result.get("success"), error=result.get("error", "恢复失败"))


@mcp.tool(name="plc_get_config", annotations={"readOnlyHint": True, "idempotentHint": True})
async def get_config() -> str:
    """获取当前项目的配置信息"""
    from _helpers import GOLDEN_ZIP, STORAGE_PATH, TIAWORKER_EXE
    if not cfg:
        return "! config_loader 未加载（检查 config.yaml 是否存在）"

    return f"""当前配置:
  项目: {os.path.basename(PROJECT_PATH)}
  PLCSIM 实例: {PLCSIM_INSTANCE}
  IP 地址: {PLC_IP}
  Golden zip: {os.path.basename(GOLDEN_ZIP)}
  Storage 路径: {STORAGE_PATH}
  TiaWorker: {'可用' if TIAWORKER_EXE.exists() else '未编译'}
  项目文件: {'存在' if os.path.exists(PROJECT_PATH) else '不存在'}
  Golden 文件: {'存在' if os.path.exists(GOLDEN_ZIP) else '不存在'}
"""
