"""Generate run_p3_complete.bat with proper CRLF line endings."""
import os
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))
from mcp_common.control_target import get_control_target

bat_path = os.path.join(os.path.dirname(__file__), '..', 'run_p3_complete.bat')

lines = []
def L(s):
    lines.append(s)

L('@echo off')
L('setlocal enabledelayedexpansion')
L('')
L('cd /d "%~dp0"')
L('')
L('set PYTHON=D:\\Python3\\python.exe')
L('set SCRIPTS=mcp-servers\\tia-mcp')
L('set GOLDEN="D:\\PLC cheng xu\\TIA PLC CHENG XU\\demo\\factory_io1_golden.zip"')
L('set STORAGE="D:\\PLC cheng xu\\TIA PLC CHENG XU\\demo\\plcsim_storage"')
L(f'set PLC_IP={get_control_target().plc_ip}')
L('')
L('echo.')
L('echo ============================================')
L('echo  AI to PLC - End-to-End Pipeline')
L('echo  PLCSIM GUI + Instance + FIO + Compile')
L('echo ============================================')
L('echo.')
L('')
L('REM ---- Step 1: Start PLCSIM Advanced GUI (the simulator window) ----')
L('echo [1/6] Starting PLCSIM Advanced GUI...')
L('%PYTHON% scripts\\start_plcsim_gui.py')
L('if errorlevel 1 (')
L('    echo [FAIL] PLCSIM GUI failed to start')
L('    echo        Make sure S7-PLCSIM Advanced V8.0 is installed')
L('    pause')
L('    exit /b 1')
L(')')
L('echo [OK] PLCSIM GUI ready')
L('echo.')
L('')
L('REM ---- Step 2: Restore PLCSIM instance from golden backup ----')
L('echo [2/6] Restoring PLCSIM instance...')
L('%PYTHON% %SCRIPTS%\\plcsim_api.py restore factoryio %GOLDEN% %STORAGE% %PLC_IP%')
L('if errorlevel 1 (')
L('    echo [FAIL] PLCSIM restore failed')
L('    pause')
L('    exit /b 1')
L(')')
L('echo [OK] PLCSIM instance running (IP=%PLC_IP%)')
L('echo.')
L('')
L('REM ---- Step 3: Launch Factory I/O ----')
L('echo [3/6] Starting Factory I/O...')
L('%PYTHON% scripts\\launch_factory_io.py')
L('if errorlevel 1 (')
L('    echo [WARN] Factory I/O launch failed (non-fatal)')
L('    echo        You can start it manually later')
L(') else (')
L('    echo [OK] Factory I/O starting')
L(')')
L('echo.')
L('')
L('REM ---- Step 4: Compile + Download ----')
L('echo [4/6] Compile + Download to PLCSIM...')
L('%PYTHON% %SCRIPTS%\\download_to_plcsim.py --compile-first')
L('if errorlevel 1 (')
L('    echo.')
L('    echo [FAIL] Download failed. Manual steps:')
L('    echo   1. Open TIA Portal GUI as Administrator')
L('    echo   2. Right-click PLC_1 - Download to device - Software')
L('    echo   3. Then run: scripts\\archive_golden.py')
L('    pause')
L('    exit /b 1')
L(')')
L('echo [OK] Download complete')
L('echo.')
L('')
L('REM ---- Step 5: Update Golden Backup ----')
L('echo [5/6] Updating golden backup...')
L('%PYTHON% scripts\\archive_golden.py')
L('if errorlevel 1 (')
L('    echo [WARN] Golden backup update failed (non-fatal)')
L(')')
L('echo.')
L('')
L('echo ============================================')
L('echo  [DONE] Pipeline Complete')
L('echo  PLCSIM [OK] - FIO [OK] - Download [OK]')
L('echo ============================================')
L('echo  Next steps:')
L('echo  1. Check PLCSIM: %PYTHON% %SCRIPTS%\\plcsim_api.py list')
L('echo  2. Open Factory I/O window to see the simulation')
L('echo  3. To stop: %PYTHON% %SCRIPTS%\\plcsim_api.py stop factoryio')
L('echo.')
L('pause')

# Write with CRLF
with open(bat_path, 'wb') as f:
    for line in lines:
        f.write(line.encode('ascii') + b'\r\n')

# Verify
with open(bat_path, 'rb') as f:
    data = f.read()

crlf_count = data.count(b'\r\n')
lf_count = data.count(b'\n') - crlf_count
ascii_only = all(b < 128 or b in (13, 10) for b in data)
print(f'Wrote {len(data)} bytes')
print(f'CRLF: {crlf_count}, Lone LF: {lf_count}, ASCII: {ascii_only}')
