"""Generate scripts/run_pnp_deploy.bat with proper CRLF + ASCII encoding for cmd.exe."""
import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bat_path = os.path.join(PROJECT_ROOT, 'scripts', 'run_pnp_deploy.bat')

lines = []
def L(s):
    lines.append(s)

L('@echo off')
L('setlocal enabledelayedexpansion')
L('')
L('REM ============================================================')
L('REM  Pick & Place One-Click Deploy')
L('REM  Create Tags -> Import SCL -> Compile -> Download -> FIO -> Robot MCP')
L('REM')
L('REM  Usage (run AS ADMINISTRATOR):')
L('REM    scripts\\run_pnp_deploy.bat')
L('REM    scripts\\run_pnp_deploy.bat --skip-tia')
L('REM ============================================================')
L('')
L('cd /d "%~dp0.."')
L('')
L('REM ---- Check admin privileges ----')
L('net session >nul 2>&1')
L('if %errorlevel% neq 0 (')
L('    echo [FAIL] This script requires Administrator privileges.')
L('    echo        Please right-click this bat file and "Run as administrator",')
L('    echo        or run from an elevated Command Prompt / PowerShell.')
L('    pause')
L('    exit /b 1')
L(')')
L('echo [OK] Running as Administrator')
L('')
L('set PYTHON=D:\\Python3\\python.exe')
L('set CREATE_TAGS=mcp-servers\\tia-mcp\\create_plc_tags.py')
L('set DEPLOY_PNP=mcp-servers\\robot-mcp\\deploy_pnp.py')
L('set TAGS_JSON=mcp-servers\\robot-mcp\\pnp_tags.json')
L('')
L('REM ---- Check Python ----')
L('if not exist "%PYTHON%" (')
L('    echo [FAIL] Python not found: %PYTHON%')
L('    echo        Please check D:\\Python3\\python.exe exists')
L('    pause')
L('    exit /b 1')
L(')')
L('')
L('echo.')
L('echo ============================================')
L('echo  Pick ^& Place One-Click Deploy')
L('echo  Python: %PYTHON%')
L('echo  Root:   %CD%')
L('echo ============================================')
L('echo.')
L('')
L('REM ---- Phase 1: Create PLC tag table ----')
L('set SKIP_TIA=0')
L('if "%1"=="--skip-tia" set SKIP_TIA=1')
L('')
L('if %SKIP_TIA% equ 0 (')
L('    echo [1/2] Creating PLC I/O tag table (PickAndPlace_IO)...')
L('    echo.')
L('    %PYTHON% %CREATE_TAGS% --tags %TAGS_JSON%')
L('    if errorlevel 1 (')
L('        echo.')
L('        echo [FAIL] Tag creation failed.')
L('        echo        Please check:')
L('        echo          1. TIA Portal V21 is open and project is not locked')
L('        echo          2. Project path in config.yaml or .env is correct')
L('        echo          3. If old tag table exists, try clearing it first')
L('        pause')
L('        exit /b 1')
L('    )')
L('    echo.')
L('    echo [OK] Tag creation complete')
L('    echo.')
L(') else (')
L('    echo [SKIP] Skipping tag creation')
L('    echo.')
L(')')
L('')
L('REM ---- Phase 2: Full deploy (SCL import + compile + download + FIO + Robot MCP) ----')
L('if %SKIP_TIA% equ 0 (')
L('    echo [2/2] Full deploy (SCL import -> compile -> download -> FIO -> Robot MCP)...')
L(') else (')
L('    echo [2/2] Starting Factory I/O + Robot MCP...')
L(')')
L('echo.')
L('')
L('%PYTHON% %DEPLOY_PNP% %1')
L('if errorlevel 1 (')
L('    echo.')
L('    echo [FAIL] Deploy failed.')
L('    echo        Please check TIA Portal and PLCSIM status.')
L('    pause')
L('    exit /b 1')
L(')')
L('')
L('echo.')
L('echo ============================================')
L('echo  [DONE] Deploy Complete!')
L('echo  AI can control the robot via Robot MCP:')
L('echo    status()     -- check robot status')
L('echo    home()       -- reset to safe position')
L('echo    pick()       -- pick from entry')
L('echo    place()      -- place to exit')
L('echo    run_cycle(5) -- auto repeat 5 cycles')
L('echo ============================================')
L('echo.')
L('pause')

# Write with CRLF + ASCII
with open(bat_path, 'wb') as f:
    for line in lines:
        f.write(line.encode('ascii') + b'\r\n')

# Verify
with open(bat_path, 'rb') as f:
    data = f.read()

crlf_count = data.count(b'\r\n')
lf_count = data.count(b'\n') - crlf_count
non_ascii = sum(1 for b in data if b > 127)
ascii_ok = non_ascii == 0

print(f'Wrote {len(data)} bytes to {bat_path}')
print(f'CRLF: {crlf_count}, Lone LF: {lf_count}, Non-ASCII: {non_ascii}')
print(f'Status: {"OK" if (ascii_ok and lf_count == 0) else "FAIL"}')
