"""
Launch Factory I/O with correct auto.cfg for PLCSIM connection.

生成 auto.cfg 指向唯一控制目标（config.yaml 的 target + factory_io 节）:
  - PLCSIM 实例名: target.plcsim_instance（经 validate_control_target 校验）
  - auto_connect = True

然后启动 Factory I/O。动态操作（改写 auto.cfg + 提权启动）前有确认门:
  交互环境输入 yes/y 确认；非交互环境未传 --yes 时 fail-closed 拒绝执行。
"""
import os
import sys
import subprocess
import time
import ctypes

# ── 配置（只从 config.yaml 读取，消灭硬编码） ──
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'mcp-servers', 'tia-mcp'))
from config_loader import cfg
from config_loader import TargetConfigurationError, validate_control_target

# 运行时由 _load_target_configuration() 填充，不硬编码。
FIO_EXE = ""
PLCSIM_INSTANCE = ""
SCENE_FILE = None  # config.yaml factory_io.scene_path 未配置时保持 None
# Factory I/O reads auto.cfg from these locations (checked in order):
#   1. Documents\Factory IO\auto.cfg (user settings)
#   2. ProgramData\Real Games\Factory IO\auto.cfg (machine settings)
# We write BOTH to ensure consistent configuration
AUTO_CFG_HOME = os.path.join(
    os.path.expanduser("~"),
    "Documents", "Factory IO", "auto.cfg"
)
AUTO_CFG_PROGRAMDATA = r"C:\ProgramData\Real Games\Factory IO\auto.cfg"


def _load_target_configuration() -> bool:
    """只从 config.yaml 唯一 target 读取实例名与 Factory I/O 路径。

    目标漂移（非 isolated_plcsim_v21 / 非 factoryio / 非 192.168.0.1）时
    由 validate_control_target 抛错，fail-closed 拒绝执行。
    """
    global FIO_EXE, PLCSIM_INSTANCE, SCENE_FILE
    try:
        target = validate_control_target()
        PLCSIM_INSTANCE = target.plcsim_instance
        FIO_EXE = cfg.factory_io.exe_path
        SCENE_FILE = cfg.factory_io.scene_path or None
    except TargetConfigurationError as exc:
        print(f"[FIO] FAIL: 控制目标配置无效，拒绝执行: {exc}")
        return False
    except Exception as exc:
        print(f"[FIO] FAIL: 无法从 config.yaml 读取控制目标: {exc}")
        return False
    return True


def _confirm_launch() -> bool:
    """确认门：动态操作（改写 auto.cfg + 提权启动 Factory I/O）前必须确认。

    交互环境输入 yes/y；非交互环境必须显式传 --yes，否则 fail-closed 拒绝。
    """
    if "--yes" in sys.argv:
        return True
    if sys.stdin.isatty():
        try:
            answer = input(
                "[FIO] 将写入 run-mode auto.cfg（含 ProgramData）并以管理员身份启动 "
                "Factory I/O。继续？[y/N] "
            )
        except EOFError:
            answer = ""
        return answer.strip().lower() in ("yes", "y")
    print("[FIO] FAIL: 非交互环境必须显式传 --yes 授权动态操作")
    return False


def check_prerequisites():
    """Verify Factory I/O is installed"""
    if not os.path.exists(FIO_EXE):
        print(f"[FIO] FAIL: Factory I/O not found at {FIO_EXE}")
        return False
    
    if SCENE_FILE and not os.path.exists(SCENE_FILE):
        print(f"[FIO] WARN: Scene file not found: {SCENE_FILE}")
        print(f"[FIO]       Factory I/O will start without auto-loading scene")
    
    return True


def _write_auto_cfg_to(path):
    """Write auto.cfg to a single location."""
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        config = (
            "# Factory I/O auto config -- generated by launch_factory_io.py\n"
            "# Format: https://docs.factoryio.com/manual/console/\n"
            "\n"
            f"drivers.siemens_s7plcsim.instance_name = '{PLCSIM_INSTANCE}'\n"
            "drivers.siemens_s7plcsim.auto_connect = True\n"
            "drivers.siemens_s7plcsim.connection_timeout = 60\n"
            "scene.start_in_run_mode = True\n"
            "ui.show_welcome_window = False\n"
        )
        
        with open(path, "w", encoding="utf-8-sig") as f:
            f.write(config)
        print(f"[FIO] auto.cfg written: {path}")
        return True
    except PermissionError:
        print(f"[FIO] WARN: Cannot write {path} (need admin rights)")
        return False
    except OSError as exc:
        print(f"[FIO] WARN: Cannot write {path}: {exc}")
        return False


def write_auto_cfg():
    """Write auto.cfg to all locations with correct PLCSIM instance name.

    Factory I/O 按注释顺序优先读取 Documents 配置（用户设置），因此:
      - Documents 写入失败 -> fail-closed 拒绝启动（可能残留指向旧目标的配置）;
      - Documents 成功而 ProgramData 失败 -> 仅告警，FIO 仍会读取 Documents 配置。
    """
    if not _write_auto_cfg_to(AUTO_CFG_HOME):
        print("[FIO] FAIL: 无法写入用户配置 Documents\\Factory IO\\auto.cfg，"
              "拒绝启动（避免 FIO 读取残留的旧目标配置）")
        return False
    if not _write_auto_cfg_to(AUTO_CFG_PROGRAMDATA):
        print("[FIO] WARN: 无法写入机器级配置 ProgramData（可能需要管理员权限），"
              "FIO 将读取 Documents 配置继续启动")
    print(f"[FIO]   instance_name = {PLCSIM_INSTANCE}")
    print(f"[FIO]   auto_connect  = True")
    print(f"[FIO]   scene         = "
          f"{os.path.basename(SCENE_FILE) if SCENE_FILE and os.path.exists(SCENE_FILE) else '(none)'}")
    return True


def launch():
    """Start Factory I/O process."""
    print(f"[FIO] Launching Factory I/O...")
    
    # Factory I/O needs admin rights for PLCSIM Softbus connection
    is_admin = ctypes.windll.shell32.IsUserAnAdmin()
    
    if is_admin:
        try:
            proc = subprocess.Popen([FIO_EXE])
        except OSError as exc:
            print(f"[FIO] FAIL: 无法启动 Factory I/O: {exc}")
            return False
    else:
        # UAC elevate
        ret = ctypes.windll.shell32.ShellExecuteW(
            None, "runas", FIO_EXE, "", None, 1
        )
        if ret <= 32:
            print(f"[FIO] FAIL: UAC elevation failed (ret={ret})")
            return False
        proc = None
    
    print(f"[FIO] Factory I/O launched (PID={proc.pid if proc else 'UAC'})")
    print(f"[FIO]   It should auto-connect to PLCSIM instance '{PLCSIM_INSTANCE}'")
    return True


def main():
    print("=" * 50)
    print("Factory I/O Launcher — AI to PLC")
    print("=" * 50)
    
    if not _load_target_configuration():
        sys.exit(1)
    
    print(f"[FIO]   PLCSIM 实例 = {PLCSIM_INSTANCE}（来自 config.yaml target）")
    print(f"[FIO]   FIO 可执行   = {FIO_EXE}")
    print(f"[FIO]   场景         = {SCENE_FILE or '(config 未配置)'}")
    
    if not _confirm_launch():
        sys.exit(1)
    
    if not check_prerequisites():
        sys.exit(1)
    
    if not write_auto_cfg():
        sys.exit(1)
    
    if not launch():
        sys.exit(1)
    
    print()
    print(f"[FIO] DONE. Factory I/O starting with PLCSIM={PLCSIM_INSTANCE}")
    print(f"[FIO]   Scene: {os.path.basename(SCENE_FILE) if SCENE_FILE and os.path.exists(SCENE_FILE) else '(none)'}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("[FIO] 已取消", file=sys.stderr)
        sys.exit(130)
    except Exception as exc:
        print(f"[FIO] FAIL: 未处理异常: {exc}", file=sys.stderr)
        sys.exit(1)
