"""
Launch Factory I/O with correct auto.cfg for PLCSIM connection.

Generates auto.cfg pointing to:
  - The correct PLCSIM instance name: factoryio
  - The correct scene file
  - auto_connect = True

Then launches Factory I/O.
"""
import os
import sys
import subprocess
import time
import ctypes

# ── Config ──
FIO_EXE = r"D:\Factory IO\Factory IO.exe"
PLCSIM_INSTANCE = "factoryio"
SCENE_FILE = os.path.join(
    os.path.expanduser("~"),
    "Documents", "Factory IO", "My Scenes",
    "测试.factoryio"
)
# Factory I/O reads auto.cfg from these locations (checked in order):
#   1. Documents\Factory IO\auto.cfg (user settings)
#   2. ProgramData\Real Games\Factory IO\auto.cfg (machine settings)
# We write BOTH to ensure consistent configuration
AUTO_CFG_HOME = os.path.join(
    os.path.expanduser("~"),
    "Documents", "Factory IO", "auto.cfg"
)
AUTO_CFG_PROGRAMDATA = r"C:\ProgramData\Real Games\Factory IO\auto.cfg"


def check_prerequisites():
    """Verify Factory I/O is installed"""
    if not os.path.exists(FIO_EXE):
        print(f"[FIO] FAIL: Factory I/O not found at {FIO_EXE}")
        return False
    
    if not os.path.exists(SCENE_FILE):
        print(f"[FIO] WARN: Scene file not found: {SCENE_FILE}")
        print(f"[FIO]       Factory I/O will start without auto-loading scene")
    
    return True


def _write_auto_cfg_to(path):
    """Write auto.cfg to a single location."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    config = (
        "# Factory I/O auto config -- generated by launch_factory_io.py\n"
        "# Format: https://docs.factoryio.com/manual/console/\n"
        "\n"
        f"drivers.siemens_s7plcsim.instance_name = '{PLCSIM_INSTANCE}'\n"
        "drivers.siemens_s7plcsim.auto_connect = True\n"
        "drivers.siemens_s7plcsim.connection_timeout = 60\n"
        "scene.start_in_run_mode = True\n"
        "ui.show_welcome_window = False\n"
    )
    
    try:
        with open(path, "w", encoding="utf-8-sig") as f:
            f.write(config)
        print(f"[FIO] auto.cfg written: {path}")
        return True
    except PermissionError:
        print(f"[FIO] WARN: Cannot write {path} (need admin rights)")
        return False


def write_auto_cfg():
    """Write auto.cfg to all locations with correct PLCSIM instance name."""
    ok = True
    if not _write_auto_cfg_to(AUTO_CFG_HOME):
        ok = False
    if not _write_auto_cfg_to(AUTO_CFG_PROGRAMDATA):
        ok = False
    if ok:
        print(f"[FIO]   instance_name = {PLCSIM_INSTANCE}")
        print(f"[FIO]   auto_connect  = True")
        print(f"[FIO]   scene         = "
              f"{os.path.basename(SCENE_FILE) if os.path.exists(SCENE_FILE) else '(none)'}")
    return ok


def launch():
    """Start Factory I/O process."""
    print(f"[FIO] Launching Factory I/O...")
    
    # Factory I/O needs admin rights for PLCSIM Softbus connection
    is_admin = ctypes.windll.shell32.IsUserAnAdmin()
    
    if is_admin:
        proc = subprocess.Popen([FIO_EXE], shell=True)
    else:
        # UAC elevate
        ret = ctypes.windll.shell32.ShellExecuteW(
            None, "runas", FIO_EXE, "", None, 1
        )
        if ret <= 32:
            print(f"[FIO] FAIL: UAC elevation failed (ret={ret})")
            return False
        proc = None
    
    print(f"[FIO] Factory I/O launched (PID={proc.pid if proc else 'UAC'})")
    print(f"[FIO]   It should auto-connect to PLCSIM instance '{PLCSIM_INSTANCE}'")
    return True


def main():
    print("=" * 50)
    print("Factory I/O Launcher — AI to PLC")
    print("=" * 50)
    
    if not check_prerequisites():
        sys.exit(1)
    
    if not write_auto_cfg():
        sys.exit(1)
    
    if not launch():
        sys.exit(1)
    
    print()
    print(f"[FIO] DONE. Factory I/O starting with PLCSIM={PLCSIM_INSTANCE}")
    print(f"[FIO]   Scene: {os.path.basename(SCENE_FILE) if os.path.exists(SCENE_FILE) else '(none)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
